### ISSUE TITLE
Creating the donation selection

### ISSUE THREAD

**Issue by CoolCoders23** [CoolCoders23/AdsTrees#9]
## User Story

>As a user interested in environmental sustainability,
>*I WANT* to be able to watch premium ads on the AdsTrees platform,
>*SO THAT* I can contribute to tree planting initiatives and support eco-friendly advertising.

### 9. Donation Selection
- **Given** I am a donator,
- **When I** choose an amount to donate,
- **Then I** should be able to select a donation amount using Stripe for payment processing.

**Comment by JideTS** [comment]
@fringemonkey89 @EhsanAsh @yega1009 

Which payment methods do you want to simulate for the MVP Stripe feature please? (Credit Cards, PayPal, Apple Pay, Google Pay...)?

**Comment by yega1009** [comment]
> @fringemonkey89 @EhsanAsh @yega1009
> 
> Which payment methods do you want to simulate for the MVP Stripe feature please? (Credit Cards, PayPal, Apple Pay, Google Pay...)?

I personally think since credit card payments is the most general its better to use that over Apple Pay, Google Pay, etc. (in real life scenario)?
For simulation purposes, however, you should feel free to use whatever is easiest.
